### ISSUE TITLE
DB : qty type problem : Supplier order

### ISSUE THREAD

**Issue by Projets-ACTI** [ATM-Consulting/dolibarr#295]
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
Quantity calculation problem received on supplier order, on quantities with two decimal places

## Environment
- **Version**: 130.1 -> 15.0.1
- **OS**: Windows NT INDUS 6.1 build 7601
- **Web server**:Apache/2.4.39 (Win64) OpenSSL/1.1.1c PHP/7.2.20
- **PHP**: 7.2.20
- **Database**: MySQL or MariaDB 5.5.5-10.4.21-MariaDB
- **URL(s)**: [*Affected URL(s)*]

## Expected and actual behavior
On a supplier order, dispatched quantity equal to the quantity ordered, but the order remains in status: partially received! Problem seen noticed on orders with quantities to two decimal places (exemple : 12.99)
llx_commande_fournisseur_dispatch -> the type of "qty" is float 
llx_commande_fournisseurdet -> the type of "qty" is double 

This creates a calculation problem for quantities with two decimal places

## Steps to reproduce the behavior
Dispatched quantity equal to the quantity ordered, but the order remains in status: partially received! Problem seen noticed on orders with quantities to two decimal places (exemple : 12.99)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging informations…)
[*Files*]

**Comment by atm-maxime** [comment]
Please use the official github repository for Dolibarr issues. This is a fork for ATM Consulting
https://github.com/Dolibarr/dolibarr
